### PR TITLE
1.19.2 Port (and some fixes)

### PR DESCRIPTION
**Pull request by JensenJ**
Hi,
I noticed the conversation in #12, so I decided to update the mod and open a PR. There are a few deprecation warnings mostly to do with the computercraft API, but for now the mod works on 1.19.2 on both Fabric and Forge. You'll probably want to bump the version number up in the gradle.properties as I left this alone. 

I also fixed a few little bugs with the train station peripheral for both Forge and Fabric. The first was if you tried to get the train's name while there was no train present, it would throw an exception in Java. The other smaller bug was the getBogeys function returned the number of carriages, so I changed the name of this function to GetCarriageCount. I would have made it so it returned the bogey count but I couldn't find an easy way to do this, so the documentation / wiki might need updating to reflect this.

### CODE REVIEW

**Comment by Luke1505** [comment]
The carriages in the code is not equal to real carriages these are the Bogeys ingame

**Comment by JensenJ** [comment]
That’s strange as when I tested it in 1.19.2 it seems to be carriages not bogeys, perhaps create changed it, I’ll have a little look into it properly.

**Comment by JensenJ** [comment]
Alright I've had a little play around with it in game, it does seem create must have changed it from when it was originally implemented here as it does do the actual carriage count now as opposed to bogey count. This may be a change between create versions used. Examples show this below. 

Three carriages (three independent bogeys)



Two carriages (2 bogeys and 1 independent bogey)

**Comment by Luke1505** [comment]
I'll be working on it to change it to the real bogey count

**Comment by JensenJ** [comment]
Would it be worth having both methods? People might find it useful for certain situations to have both bogey count and carriage count available to query.

**Comment by Luke1505** [comment]
yeah I think I'll implement both ways

**Comment by DegaZZZ** [comment]
Will this Pull Request be released at least in someway? Because for some reason I cannot compile it at all.

**Comment by Luke1505** [comment]
Right now we are working on the mod when you want to use it then download the version you need cause this is the in development version

**Comment by LeMoonStar** [comment]
@Luke1550 is it possible that you closed this PR on accident as you tought it was an issue (regarding the comment you responded to)? I see no reason to close it, as the PR still seems active. Might wanna reopen it.

**Comment by Luke1505** [comment]
This PR was intentional closed cause the changes were irrelevant cause all of that could've been mentioned in a issue where I can respond to the irrelevant changes and just implement these that are correct/nessecary

**Comment by Luke1505** [comment]
And to the 1.19.2 part we are already working on one so

**Comment by LeMoonStar** [comment]
> This PR was intentional closed cause the changes were irrelevant cause all of that could've been mentioned in a issue where I can respond to the irrelevant changes and just implement these that are correct/nessecary 

If you want people to contribute to a project, you should documment such practices. So not just close a PR/Issue, but also comment where exactly discussion will be continued, and why the resuest has been closed.

Further more: Are you using code, the creator of this Pull Request created? If so, are you using their original commits and or credit them? If you don't, do you have their permission to do so?

**Comment by Luke1505** [comment]
I do not use code of the contributor of this PR , i closed that PR cause we
said everywhere that we will implement 1.19 in the next release which is
almost done in my Local copy so we can compile all versions Simultaneously
which this PR would not provide , i took the advice that the GetWaggons(or
whatever it was called gives back the Bogeys) and changed that to smth else

**Comment by Luke1505** [comment]
I meant that the getBogeys is now getCarrieges (or whatever) and the getBogeys is in work to return the correct number of Bogeys

**Comment by LeMoonStar** [comment]
> I do not use code of the contributor of this PR , i closed that PR cause we
> said everywhere that we will implement 1.19 in the next release which is
> almost done in my Local copy so we can compile all versions Simultaneously
> which this PR would not provide , i took the advice that the GetWaggons(or
> whatever it was called gives back the Bogeys) and changed that to smth else

Thats all fine. Yet, It would be considerably nicer, if you would comment the exact reason for a close of an issue before closing it, espsically when it happens after mutliple days of inactivity. Even if th was previously discussed, a short summary of the reason always makes sense and helps people be up to date.

And just out of curiosity: is there a reason you keep your changes on your local machine, instead of pushing them to some branch on this repository or a fork? It would keep people up to date on the progress, enable people to test it and suggest improvements. It also is safer than keeping it on your local machine, which is way more likely to fail and loose data.

**Comment by Luke1505** [comment]
I work like that I want to finish a part and then push it .

Since it's still ongoing process I have it on my Local Machine next Year
when we work is not that stressy I'll get back working on it

**Comment by Luke1505** [comment]
And FYI when you want to add something or have something in mind just let
me Know on discord cause there I am more active than on GH (Luke |
GOD#1505)

**Pull request closed without merging**
